### ISSUE TITLE
请问进程模式的白名单（代理全部进程）应该如何设置？

### ISSUE THREAD

**Issue by Kylejustknows** [AmazingDM/Netch-ForOwnUse#1]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述**
简明扼要地描述需要的功能

**额外信息**
看了你的魔改简介，说和原版相比，加入了进程模式白名单。
但是看了所有的新手+进阶说明，都没找到设置方式。
软件自带的mode选择里，也没有相应的模板。
麻烦您，简单提示一下，如何开启进程模式的白名单？

**Comment by AmazingDM** [comment]
README没更新（懒 逃
在设置开启进程白名单后将**代理全局所有进程**，只有选择的mode内进程以及netch相关启动进程不会被代理，具体固定绕过的程序在这里 https://github.com/AmazingDM/Netch-ForOwnUse/blob/4eb498891b19c804afbb9aad40715ef70a276816/Netch/Controllers/NFController.cs#L221

**Comment by Kylejustknows** [comment]
我弄明白了。我给其他用户补充一下：

总设置里”开启白名单“后，进程模式1的代理进程列表会”翻转“。

举例：

不开白名单选项时，
选bf1游戏模式，只有bf1.exe走代理；其他所有软件直连；

打开白名单选项后,
选bf1游戏模式，变成所有软件都走代理，bf1.exe反而变成直连。
