### ISSUE TITLE
是否提供选项以禁用强制网卡DNS设置？

### ISSUE THREAD

**Issue by chengyuhui** [AmazingDM/Netch-ForOwnUse#7]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述**
（主项目里面似乎还没有这个设置DNS的功能，就在这里提了）

在进程模式下将网卡的DNS设置为8.8.8.8在部分情况下会导致访问国内网站极其缓慢（成都移动和联通均可复现，B站和微博基本上就打不开了）

我理解这么搞可能是为了防止DNS污染，但是对于游戏本身完全不受DNS污染的情况，能否禁用这个功能？每次都要去手动改回来...

**额外信息**

**Comment by AmazingDM** [comment]
![image](https://user-images.githubusercontent.com/10679055/91015128-2a16f400-e5da-11ea-862d-b81bc1fbd8f6.png)
最新actions构建已支持此功能，1.6正式版不久后更新到Release
